# Config file for automatic testing at travis-ci.org

language: python
python:
  - 3.6
  - 3.5
  - 3.4
  - 2.7

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -U tox-travis

# Command to run tests, e.g. python setup.py test
script: tox


deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: bidhan-a
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: bidhan-a/singularity_compose
    python: 3.6
